### ISSUE TITLE
Hacking Session

### ISSUE THREAD

**Issue by JoopAue** [fptudelft/IN4389#27]
Dear, @fptudelft/in4389-2015 

@MartinRogalla and I have access to the v/d Poelzaal today from 9:00 until 14:30.
If you are working on Reactive Programming today you are free to join us!
There is plenty of space and free tea down the hall.

**Comment by AlpineMutts** [comment]
![:D](http://media.giphy.com/media/6IQ9o86ThLoGY/giphy.gif)

**Comment by gewoonrik** [comment]
Cool we'll be there in half an hour!

**Comment by JoopAue** [comment]
@GeorgiKhomeriki,
I have a question about the implementation of a monad and how to use it.
Can I find you somewhere today?

**Comment by gkhom** [comment]
Can you come by the office on the 9th floor (09.250) around 16:00?

**Comment by JoopAue** [comment]
Yes, see you then!
